### ISSUE TITLE
Naomi report updates to-do

### ISSUE THREAD

**Issue by jeffeaton** [mrc-ide/naomi#166]
Making notes here as reviewing report draft:

Small fixes:
- [x] Swap order of UNAIDS and Naomi logos in header? What do you think?
- [x] Change title 'District HIV estimates' to 'Subnational HIV estimates'
- [x] Add commas if multiple survey IDs (`paste(..., collapse = ", ")`)
- [x] Convert calibration option labels to human readable.  Can use the same labels as specified for the drop downs in Naomi web tool.
- [x] Indicate whether ANC testing and ART data were included and which years if so.
- [x] Remove line header anchors. (Default changed in recent update of knitr. There's an option to specify in the YAML header to revert to old behaviour)
- [x] Adjust number formatting in table to be consistent with `inst/metadata/metadata.csv` specifications
       - One decimal digit for prevalence, ART coverage, and incidence per 1000
       - PLHIV and number on ART rounded to nearest 100
       - Infections rounded to nearest 10
- [x] Sort table by `area_sort_order`

Medium effort: 
- [x] Update date in header to reflect the reference data for estimates and date produced. E.g.: **September 2018 (report 27 November 2020)**.
       I think that doing this will involve restructuring the report so most of the data inputs are done outside the report and
       passed as parameters, so it's a bit of effort.

**Comment by jeffeaton** [comment]
I'm adding some more issues on report review:


-----
![image](https://user-images.githubusercontent.com/7427899/102992853-fa3e1580-4513-11eb-9490-d07e6b306e6c.png)
- [ ] Calibration sex/age strata only shown if calibration is applied (no need if 'None'
- [ ] New infections calibration level is missing
- [ ] Awareness of status calibration options are missing
-----

![image](https://user-images.githubusercontent.com/7427899/102992972-35d8df80-4514-11eb-90b3-220271a669a3.png)

- [ ] PLHIV and new infections counts should be age 15+ (rates should be 15-49 as in next figure)
- [ ] Number formatting in key legend

-----

![image](https://user-images.githubusercontent.com/7427899/102993021-56a13500-4514-11eb-8dd9-407a3711c5fa.png)

- [ ] No decimal place for ART coverage legend.
- [ ] One decimal place for Incidence per 1000 legend.

-----
![image](https://user-images.githubusercontent.com/7427899/102993113-7e909880-4514-11eb-9d45-2aeacc21bd8b.png)
![image](https://user-images.githubusercontent.com/7427899/102993184-9b2cd080-4514-11eb-92d3-00c06dc116d4.png)

- [ ] __HIV incidence per 1000__ title getting cut off
- [ ] One decimal for national prevalence
- [ ] One decimal for incidence per 1000
- [ ] It would be nice to include uncertainty range for national figures

**Comment by jeffeaton** [comment]
@rtesra -- One more request on this:

- [ ] Make district borders thinner on the chloropleth plot. 

This might make the differences between districts stand out m ore.

![image](https://user-images.githubusercontent.com/7427899/105423222-06191680-5c3d-11eb-9fa8-496e4c50bde7.png)
